// Generates the files that are derived from the palettes: the curtain style sheets and the
// icons. Run with `node tools/make-assets.mjs` after changing a palette in defaults.js.
import { writeFileSync } from 'node:fs';
import { deflateSync, crc32 } from 'node:zlib';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ext = join(dirname(fileURLToPath(import.meta.url)), '..', 'extension');
await import('../extension/defaults.js');
await import('../extension/content/color.js');
const { PALETTES, DEFAULTS } = globalThis.LULL;
const C = globalThis.Lull.color;

// ---- curtains -----------------------------------------------------------------

const SKIP = 'img,video,canvas,picture,svg,svg *,iframe,embed,object,[style*="background-image"]';
for (const palette of Object.keys(PALETTES)) {
  const t = C.makeTheme({ ...DEFAULTS, palette }, false).css;
  const css = `/* Generated by tools/make-assets.mjs. Paints the page dark before any script runs, so there is
   no white flash. main.js switches it off by setting data-lull-ready on <html>. */
html:not([data-lull-ready]){background-color:${t.bg}!important;color-scheme:dark!important}
html:not([data-lull-ready]) body,html:not([data-lull-ready]) body :not(${SKIP}){background-color:${t.bg}!important;color:${t.fg}!important;border-color:${t.border}!important}
`;
  writeFileSync(join(ext, 'content', `curtain-${palette}.css`), css);
  console.log(`curtain-${palette}.css`, t.bg, t.fg);
}

// ---- icons ----------------------------------------------------------------------
// A crescent on a rounded slate square, drawn by supersampling so the edges are smooth.

function png(size, pixels) {
  const chunk = (type, data) => {
    const body = Buffer.concat([Buffer.from(type), data]);
    const out = Buffer.alloc(body.length + 8);
    out.writeUInt32BE(data.length, 0);
    body.copy(out, 4);
    out.writeUInt32BE(crc32(body) >>> 0, body.length + 4);
    return out;
  };
  const head = Buffer.alloc(13);
  head.writeUInt32BE(size, 0);
  head.writeUInt32BE(size, 4);
  head[8] = 8; // bit depth
  head[9] = 6; // RGBA
  const raw = Buffer.alloc((size * 4 + 1) * size);
  for (let y = 0; y < size; y++) pixels.copy(raw, y * (size * 4 + 1) + 1, y * size * 4, (y + 1) * size * 4);
  return Buffer.concat([
    Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]),
    chunk('IHDR', head),
    chunk('IDAT', deflateSync(raw)),
    chunk('IEND', Buffer.alloc(0)),
  ]);
}

function icon(size) {
  const bg = [35, 38, 45];
  const moon = [217, 212, 199];
  const pixels = Buffer.alloc(size * size * 4);
  const N = 4;
  const radius = 0.22;
  const insideSquare = (x, y) => {
    const dx = Math.max(radius - x, x - (1 - radius), 0);
    const dy = Math.max(radius - y, y - (1 - radius), 0);
    return dx * dx + dy * dy <= radius * radius;
  };
  const insideMoon = (x, y) =>
    Math.hypot(x - 0.47, y - 0.52) <= 0.3 && Math.hypot(x - 0.6, y - 0.41) > 0.25;
  for (let py = 0; py < size; py++) {
    for (let px = 0; px < size; px++) {
      let square = 0;
      let crescent = 0;
      for (let sy = 0; sy < N; sy++) {
        for (let sx = 0; sx < N; sx++) {
          const x = (px + (sx + 0.5) / N) / size;
          const y = (py + (sy + 0.5) / N) / size;
          if (!insideSquare(x, y)) continue;
          square++;
          if (insideMoon(x, y)) crescent++;
        }
      }
      const i = (py * size + px) * 4;
      const mix = square ? crescent / square : 0;
      for (let c = 0; c < 3; c++) pixels[i + c] = Math.round(bg[c] + (moon[c] - bg[c]) * mix);
      pixels[i + 3] = Math.round((square / (N * N)) * 255);
    }
  }
  return png(size, pixels);
}

for (const size of [16, 32, 48, 128]) {
  writeFileSync(join(ext, 'icons', `icon${size}.png`), icon(size));
  console.log(`icon${size}.png`);
}
